### ISSUE TITLE
Fetch version from source

### ISSUE THREAD

**Issue by pierrejoye** [FriendsOfPHP/pickle#114]
Version should be grabbed from the sources, only. Not even from package.xml.

It requires some refactoring, Package::factory and other areas.

**Comment by weltling** [comment]
Pah, in #113 i did one commit to the convert command just so it works for now. Now, as we go without version in composer.json, the other side of the coin is - the convert command needs to save the stability into the version macro. If we later want to fetch it from there, otherwise it'll get lost.

**Comment by pierrejoye** [comment]
It does not need to. The stability is part of the version. See the semver
link to packagist.org. this is the whole point :)

**Comment by pierrejoye** [comment]
VersionParser will provide both version and stability, based on semver definition.

**Comment by weltling** [comment]
Ok, this was already implemented, i only had to fix how source/binary release behaves. Now, for the source release, the composer.son from the sources will be used. That composer.json doesn't need to have any version information. For the binary release, the version information will be included.

I also adjusted the convert command to not to include the version into JSON. The versions are read from the headers, except a package were fetched or versions come from the user input, so then we have to build the paths to fetch some extensions.

With this, looks like this issue is done.
